# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev32+gc0a3ea9.d20230211"
__version_tuple__ = version_tuple = (0, 1, "dev32", "gc0a3ea9.d20230211")
